[build]
  command = "npm install"
  publish = "public"            # This is your static assets folder
  functions = "netlify/functions"  # Where your serverless functions are stored

[functions]
  node_bundler = "esbuild"      # Helps Netlify bundle dependencies like ejs properly

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
